### ISSUE TITLE
自荐一个小工具项目：load-markdown-image

### ISSUE THREAD

**Issue by junbin123** [xucz/awesome-1kb#3]
## load-markdown-image

一个将 markdown 文件中的网络图片替换为本地图片的npm包。
支持识别图片格式、自定义存放图片文件夹名称。

github：https://github.com/junbin123/load-markdwon-image
npm：https://npmjs.org/package/load-markdown-image

**Comment by xucz** [comment]
感谢推荐，项目已收录
